-- AlterTable
ALTER TABLE `lot` MODIFY `status` ENUM('DRAFT', 'AVAILABLE', 'OFFER_ACCEPTED', 'PICKUP_SCHEDULED', 'HANDED_OVER', 'RECEIVED_BY_RECYCLER', 'CLOSED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT';
